### ISSUE TITLE
Domes are capped at too low a height

### ISSUE THREAD

**Issue by TheLoneWolfling** [BrainSlugs83/NewBiospheresMod#10]
MC has a world height of 256 blocks, and has for a while now. As such, capping world generation at 127 (128?) blocks shouldn't be necessary.

**Comment by BrainSlugs83** [comment]
Hmm... even though I up WORLD_HEIGHT to 256 (and thus WORLD_MAX_Y to 255), it seems to still get cut off at 128.

If there truly isn't a limit in Minecraft, then there's something else in the mod that's holding it back.  I'll have to dig a little deeper.

**Comment by BrainSlugs83** [comment]
Derp.  It's probably xShift and zShift. XD

**Comment by BrainSlugs83** [comment]
Well, that's super weird.

It's not xShift or zShift -- but it generates two rows of biospheres... -- I tried even manually capping it at 127 -- so the only difference is, I'm handing back a larger array -- and nothing else (on my end) is touching that array -- so I have no idea where the second layer of biospheres is coming from...

I wonder if Minecraft is copying the arrays over into it's own memory structure and overlapping them by accident or something. -- Super fucking weird.

**Comment by BrainSlugs83** [comment]
Hmm -- found [this](http://www.minecraftforge.net/forum/index.php?topic=12857.0) -- looks like vanilla world gen only supports Y values up to 127 -- but there's something extra in Forge (with some refactoring) that will let me use higher values properly.

**Comment by BrainSlugs83** [comment]
HA! -- Figured it out -- it looks like if you use the constructor that takes in the metadata array that this "just works" (crazy!).

**Comment by BrainSlugs83** [comment]
This is checked-in.
