### ISSUE TITLE
No way to add custom ores with specific metadata / NBT data.

### ISSUE THREAD

**Issue by TheLoneWolfling** [BrainSlugs83/NewBiospheresMod#11]
There are a number of mods that currently have a "generic" ore block, where the different metadatas refer to different types of ores. For mods that do this and do not have specific names for different metadatas, it is currently impossible to add those ores.

One could argue that it is an issue with these mods, but regardless it isn't possible currently.

For instance, I cannot find a way to add the ores from [Cogs of the machine](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1442605-1-7-10-forge-cogs-of-the-machine-v0-1-4pre1-back) to the ore orbs.

**Comment by BrainSlugs83** [comment]
Thanks for pointing this out, I'll take a look.  Need to figure out how to insert a block with metadata anyway.

*(FYI, my aim is to be as compatible with other mods as possible -- which, I admit, is still a ways off -- but, unless there's like a technical blocker in another mod that absolutely prevents me from doing something, I'm unlikely to argue the other mod should be changed instead.  Mainly, because, If one popular mod is doing it a certain way, there's probably another 10 not as popular ones doing it that way too. -- Also, as a newbie modder, I recognize that I'm probably doing certain things in a way that's completely wrong. -- This is a good feature request, btw.  Thank you.)*

**Comment by TheLoneWolfling** [comment]
Good to know, thanks! Modders seem to fall into two categories on that front.

The easiest way I know of would be to split the value on the *last* instance of ':', then treat the first part as the block name and the second as the metadata. For instance, "FooBar:2" would be treated as "FooBar" with a metadata of 2.

That just means changing `Utils.ParseBlock` slightly. Something along the lines of the following would work (though beware fencepost errors) - although Java doesn't allow multiple returns so have fun with that:

	public static Block parseBlock(String blockNameOrId, Block fallback) {
		Block b = Block.getBlockFromName(blockNameOrId);
		if (b != null)
			return b, 0;
		int sIndex = blockNameOrId.lastIndexOf(':');
		if (sIndex == -1)
			return fallback;
		b = Block.getBlockFromName(blockNameOrId.substring(0, sIndex-1));
		int meta = Integer.valueOf(blockNameOrId.substring(sIndex+1));
		assert (0 <= meta && meta < 16);
		return b, meta;
	}

 Also: by the way I'm pretty sure that `Block.getBlockFromName` already checks for numeric IDs - I don't think you need to check yourself beforehand.

**Comment by BrainSlugs83** [comment]
Yeah, I'm thinking I will probably just need a wrapper class for Block and Metadata -- Metadata is always an int? -- I'll have to do some research here.

**Comment by TheLoneWolfling** [comment]
Metadata is a nibble - 4 bits, i.e. 0-15, inclusive. But Java being Java, there's no way to use anything below a byte, and byte arithmetic is a pain.

**Comment by BrainSlugs83** [comment]
Wow, and apparently, java has [no byte literals](http://stackoverflow.com/questions/5193883/how-do-you-specify-a-byte-literal-in-java).  Go Java!

**Comment by BrainSlugs83** [comment]
Hmmm... what about blocks from other mods that start with modPrefix + ":" ...

**Comment by TheLoneWolfling** [comment]
Yep.

About the only annoyance that could be a problem with the approach I outlined would be if both `foo` and `foo:1` were valid names, for different blocks, in which case you couldn't get `foo` with a metadata of 1 - but I doubt that will happen. Although famous last words and all that.

**Comment by BrainSlugs83** [comment]
What could possibly go wrong? -- heh. ;-)

ANyway, this should be fixed in the latest push.  Let me know and re-open if it isn't.
