### ISSUE TITLE
Incorrect biome surface blocks

### ISSUE THREAD

**Issue by TheLoneWolfling** [BrainSlugs83/NewBiospheresMod#13]
For example:

Seed of `Hello`:

![2015-04-11_14 56 27](https://cloud.githubusercontent.com/assets/2056317/7102600/6695d8a4-e05b-11e4-830c-1fa20f7685ee.png)

**Comment by BrainSlugs83** [comment]
What is incorrect about the surface block? -- It looks like sand blocks with cactuses, yeah?

Are you saying the biome is wrong? (That it's a Birch Forest Hills biome, and not a Desert biome?)

I think this is similar to [Issue 5](https://github.com/BrainSlugs83/NewBiospheresMod/issues/5), right?

**Comment by TheLoneWolfling** [comment]
Yes, that's what I'm saying. It's a birch forest hills biome, but the surface is decorated as though it was a desert.

**Comment by TheLoneWolfling** [comment]
Seems to be fixed with the experimental build linked in #24.
