### ISSUE TITLE
Weird patchworks of biomes.

### ISSUE THREAD

**Issue by TheLoneWolfling** [BrainSlugs83/NewBiospheresMod#14]
For example: seed of "HELLO":

![2015-04-11_14 57 30](https://cloud.githubusercontent.com/assets/2056317/7102602/87d1ddb0-e05b-11e4-8a26-eda943dda575.png)
![2015-04-11_14 57 06](https://cloud.githubusercontent.com/assets/2056317/7102603/87d269f6-e05b-11e4-9a79-3e5882cc58b8.png)
![2015-04-11_14 57 08](https://cloud.githubusercontent.com/assets/2056317/7102604/87d2c356-e05b-11e4-8890-dc9e08577dc1.png)
![2015-04-11_14 57 27](https://cloud.githubusercontent.com/assets/2056317/7102601/87d1237a-e05b-11e4-9177-c40a88f1ed39.png)
![2015-04-11_14 57 29](https://cloud.githubusercontent.com/assets/2056317/7102605/87d4ba8a-e05b-11e4-9cf4-73e333ddfd18.png)

There are similar (and even weirder) combinations elsewhere. Note that said 1x1 patchworks occur all across the biosphere.

**Comment by BrainSlugs83** [comment]
What exactly are we looking at?  Are those glass dome blocks? -- Can you attach your config file?

**Comment by TheLoneWolfling** [comment]
Default config, although I'll attach it in a minute if you wish.

Look at the biome in the F3 menu. I'm looking down within a dome.

**Comment by BrainSlugs83** [comment]
No need to attach default config.  I'll take a look.

**Comment by BrainSlugs83** [comment]
Either I don't understand, or I can't reproduce the issue.

I went to that location, and the ground looks normal to me.  The blocks all seem to have the right texture (on yours it seems the block texture gets much smaller on the lower blocks, is that right?).

What am I missing?

![Close up](https://i.imgur.com/GEilKl2.png)

![Zoomed Out](https://i.imgur.com/i5mIjR4.png)

**Comment by TheLoneWolfling** [comment]
Yeah, I tend to use a wider field of view, hence why things can look distorted.

Alright, looking into it more, it appears to be inconstantant. Don't you love Hisenbugs? I cannot seem to reproduce that seed myself, which is... worrying.

...Uh-oh. That's not good. I exited and restarted a world, and now I have a different pattern of biomes (!). So *something weird* is going on:

Once you exit and restart the game for the first time after generating a chunk, the biomes change. That's not good at all.

Look at [this](https://www.dropbox.com/s/q8g0atoqveqao3u/Weird.zip?dl=0) saved world. Go to x109 / y80 / z-135. Notice that it's a Savanna Plateau biome.

Now go to the new world screen and copy the world. Go to the same coordinates. Notice that it is a Forest biome. Then restart the game, and notice it's a Savanna Plateau biome.

**Comment by BrainSlugs83** [comment]
Whoa, yeah -- the biome generation is inconsistent per the seed? -- That can't be good at all.

I don't have access right now, so I'll have to take a look tonight.

To be sure: the world you attached -- was it generated with version 0.85? or with a previous version?

(I want to determine if it's broken consistently due to an accidental change in code between version .8 and .85, or if it is just plain not based on the seed in a reproducible manner -- the latter has worse implications IMHO, but probably easier to fix...)

I suppose, in the future, I should add a property to the world stating which version of the mod generated it (and never replace it if it's already there), so that I can determine these things without needing to ask. -- Maybe add some other debugging properties as well...

**Comment by BrainSlugs83** [comment]
On a third note: Are we still talking about the same bug, or is this a new bug?

**Comment by TheLoneWolfling** [comment]
0.85, and I don't know if the weird patchworks are purely due to the biomes changing on generation or not. I'd say make a new bug and figure out this bug only when the other one's fixed.

I'll see if I can get the same weirdness in 0.8.

**Comment by TheLoneWolfling** [comment]
Yep, it also happens in 0.8. So something screwy is going on - I've opened a new bug for it - #24.

**Comment by BrainSlugs83** [comment]
Woot, I'll take a look.

**Comment by TheLoneWolfling** [comment]
Seems to be fixed with the experimental build linked in #24.
