### ISSUE TITLE
Mod id for /give purposes contains spaces

### ISSUE THREAD

**Issue by TheLoneWolfling** [BrainSlugs83/NewBiospheresMod#17]
As a result you cannot /give any blocks that New Biospheres Mod adds, as /give doesn't have any way to escape spaces.

(Well, you sort of can, but you have to do it numerically, which means you have to already know the ID)

Not much of a problem for now, but something to keep in mind for if NBM adds any actual blocks.

**Comment by BrainSlugs83** [comment]
I wasn't aware of this restriction.

I can remove the spaces from the name and fix it -- but I think people might lose their config files (also have a space in them) -- will have to check if there is someway to migrate it forward.

Also -- those added blocks are kind of a hack (to fix Issue spawning and lighting issues), not really sure we want people "/giving" them -- OTOH, some power user might need to repair a griefed dome or something... so might as well fix it now before the mod gets anymore popular (so the config thing will affect less users).

**Comment by BrainSlugs83** [comment]
Should be fixed (no more spaces in Mod Id -- and if the config file is missing, but one by the old name does exist, it's renamed at start-up).

**Comment by TheLoneWolfling** [comment]
I wouldn't have called this a high priority bug, but OK. Glad it's fixed.
