### ISSUE TITLE
Custom biome weights are overwritten to defaults

### ISSUE THREAD

**Issue by TheLoneWolfling** [BrainSlugs83/NewBiospheresMod#28]
Found this out while I was trying to mess with swamp generation and wanted lots of swamps to see if things made sense.

It appears that NBM overwrites the config with the default values for biome weights on exit.

**Comment by BrainSlugs83** [comment]
So the reproduction steps I'm hearing are: 
1. Set custom Biome weights.
2. Exit Minecraft.
3. Relaunch Minecraft and verify Biome weights.

Expected Behavior:
Custom Biome Weights are preserved.

Actual Behavior:
They are restored to defaults.

Is this correct?

**Comment by BrainSlugs83** [comment]
Trying to repro this and running into another issue -- when I build the latest version, there is no Configure / Disable options... is it just me?

**Comment by BrainSlugs83** [comment]
Sorry, this was blocked for awhile by #40.  I'm able to reproduce this issue and will look into it now.

**Comment by BrainSlugs83** [comment]
Fixed!
